# mode: ruby


boxes = [
    {
        :name => "data-one",
        :eth1 => "192.168.100.10",
        :mem => "256",
        :cpu => "1"
    },
	{
        :name => "data-two",
        :eth1 => "192.168.100.11",
        :mem => "256",
        :cpu => "1"
    },
    {
        :name => "web-one",
        :eth1 => "192.168.100.12",
        :mem => "256",
        :cpu => "1"
    },
    {
        :name => "web-two",
        :eth1 => "192.168.100.13",
        :mem => "256",
        :cpu => "1"
    },
    {
        :name => "mq-one",
        :eth1 => "192.168.100.14",
        :mem => "256",
        :cpu => "1"
    },
    {
        :name => "mq-two",
        :eth1 => "192.168.100.15",
        :mem => "256",
        :cpu => "1"
    }   
]

Vagrant.configure(2) do |config|

  config.vm.box = "cms"

  # Turn off shared folders
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]

      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
        v.name = opts[:name]
      end

       config.vm.network :private_network, ip: opts[:eth1]
       #config.vm.network "public_network" #, bridge: "en1: Wi-Fi (AirPort)"
       config.vm.synced_folder "D://application", "/application"
       config.vm.synced_folder "D://projects", "/projects"
       config.vm.synced_folder "D://projects//php-cms", "/srv/www"
    end
  end
end
